### ISSUE TITLE
Tutorial Logic Kullanımı

### ISSUE THREAD

**Issue by kerimbr** [AppismDev/bimateryal_flutter#11]
TutorialView içersindeki logic işlemleri TutorialLogic sınıfına taşınmalıdır.

ör: 

**lib/views/TutorialPage/tutorial_view.dart**
`  int _pageIndex = 0;`

Şuraya taşınmalıdır;
**lib/views/TutorialPage/tutorial_logic.dart**
`RxInt pageIndex = 0`

**Comment by Emirgms** [comment]
yapıldı.
